console_title_template = ' {{ .Folder }} :: {{if .Root}}Admin{{end}}'
terminal_background = 'p:t-background'
version = 3
final_space = true

[palette]
  blue-bell = '#9aa5ce'
  blue-black = '#565f89'
  celeste-blue = '#b4f9f8'
  light-sky-blue = '#7dcfff'
  main-bg = '#24283b'
  pastal-grey = '#cfc9c2'
  pistachio-green = '#9ece6a'
  t-background = 'p:main-bg'
  terminal-black = '#414868'
  terminal-blue = '#7aa2f7'
  terminal-green = '#73daca'
  terminal-magenta = '#bb9af7'
  terminal-red = '#f7768e'
  terminal-white = '#c0caf5'
  terminal-yellow = '#e0af68'
  white-blue = '#a9b1d6'

[secondary_prompt]
  template = '‚ûú '
  foreground = 'p:terminal-blue'
  background = 'transparent'

[transient_prompt]
  template = '‚ûú '
  foreground = 'p:terminal-blue'
  background = 'p:t-background'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '‚ûú '
    foreground = 'p:terminal-blue'
    background = 'transparent'
    type = 'text'
    style = 'plain'

  [[blocks.segments]]
    template = '<b>{{ .Path }}</b> <p:light-sky-blue>‚ö°</>'
    foreground = 'p:terminal-magenta'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    template = '({{ .HEAD}})'
    foreground = 'p:light-sky-blue'
    type = 'git'
    style = 'plain'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:terminal-red{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0)}}p:light-sky-blue {{ end }}', '{{ if gt .Ahead 0 }}p:terminal-blue{{ end }}', '{{ if gt .Behind 0 }}p:celeste-blue{{ end }}']

    [blocks.segments.properties]
      branch_icon = 'Óú• '
      fetch_status = true

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'p:terminal-red'
    background = 'transparent'
    template = ' {{ .FormattedMs }} '

    [blocks.segments.properties]
      threshold = 1000
      style = 'austin'


  [[blocks.segments]]
    template = ' ÔÄç'
    foreground = 'p:terminal-red'
    type = 'status'
    style = 'plain'

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  overflow = 'hide'

  [[blocks.segments]]
    template = 'Óúò {{ .Full }} '
    foreground = 'p:pistachio-green'
    type = 'node'
    style = 'plain'

  [[blocks.segments]]
    template = 'ÓúΩ {{ .Full }} '
    foreground = 'p:terminal-blue'
    type = 'php'
    style = 'plain'

  [[blocks.segments]]
    template = 'Óàµ {{ .Full }}'
    foreground = 'p:terminal-yellow'
    type = 'python'
    style = 'plain'

  [[blocks.segments]]
    template = 'Óò§ {{ .Full }}'
    foreground = 'p:terminal-magenta'
    type = 'julia'
    style = 'plain'

  [[blocks.segments]]
    template = 'Óûë {{ .Full}}'
    foreground = 'p:terminal-red'
    type = 'ruby'
    style = 'plain'

  [[blocks.segments]]
    template = 'Ô≥ë {{ .Full}}'
    foreground = 'p:light-sky-blue'
    type = 'go'
    style = 'plain'

  [[blocks.segments]]
    foreground = 'p:white-blue'
    type = 'command'
    style = 'plain'

    [blocks.segments.properties]
      command = 'git log --pretty=format:"Óú• %cr" -1 || date +%H:%M:%S'
      shell = 'bash'

[block]
  alignment = "right"
  filler = "."

  [[blocks.segments]]
    foreground = 'p.light-sky-blue'
    type = 'command'
    style = 'plain'
    template = 'üé® {{ .Output }}'
 
    [blocks.segments.properties]
      shell = "bash"
      command = "~/.config/ohmyposh/art-env.sh || ''"

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '‚ñ∂'
    foreground = 'p:pistachio-green'
    type = 'text'
    style = 'plain'

